### ISSUE TITLE
bug(digests): Multible Tags get pushed with diferent SHA digests

### ISSUE THREAD

**Issue by k3rnelpan1c-dev** [redhat-actions/push-to-registry#26] opened 2021-02-20 15:43 UTC
### Description

Pushing an image with more than one tag seems to result in the same image pushed with a different digest per pushed tag.

### To reproduce

1. add a basic GH workflow using the `buildah-build` and `push-to-registry` action
2. build a basic test image with at least 2 tags (e.g. `tags: unstable {{ github.sha }}`)
3. let the workflow push the image with both tags
4. see the result in the registry (2 digests for the same image :confused:)

### Example

I stumbled over this while working on some PRs for `dohq/dockerhub_ratelimit_exporter` where I wanted to add an incremental build workflow and ultimately release workflow pushing a Container Image.
I tried pushing to both the new `ghcr.io` (tried formats: docker and oci) as well as `docker.io` (tried format: docker), both resulting in the image getting pushed successfully, but with 2 different digests for the two tags.

[my Fork's `inc-build` Workflow](https://github.com/k3rnelpan1c-dev/dockerhub_ratelimit_exporter/blob/master/.github/workflows/inc-build.yml)
[the result on `ghcr.io`](https://github.com/users/k3rnelpan1c-dev/packages/container/package/dockerhub_ratelimit_exporter)

![image](https://user-images.githubusercontent.com/69395733/108600938-2ce07f00-739a-11eb-8884-aed28ba44324.png)
The "2" tags in the screenshot are the result of the **same** inc-build => the same image.

### Alternative "solution"

Use the docker based alternative actions to build and push, as these don't seem to face this problem :frowning_face:

**Comment by tetchel** [comment] 2021-02-20 18:51
Interesting.. I don't see this problem with our test workflow's images. Both tags are `35665...`

![image](https://user-images.githubusercontent.com/8888438/108605551-b3896200-7382-11eb-99ef-5c3bde4d78ee.png)

We will have a look

**Comment by tetchel** [comment] 2021-02-20 18:59
This looks suspiciously like https://github.com/containers/podman/issues/6496

**Comment by k3rnelpan1c-dev** [comment] 2021-02-20 19:09
Interesting, I will try and give Quay a try to see if I can replicate this there too (which I should not be able too if your test workflow is anything to go by). I will report back as soon as I have the results.
Regarding the Podman Issue you liked, I should have  read up on that too till then :wink:

**Comment by tetchel** [comment] 2021-02-20 19:32
In the main branch, I've put in a commit which logs the digest after each push instead of at the end. So we can detect this one step earlier.

This confirms again that at least in our test workflow, the digests match.
![image](https://user-images.githubusercontent.com/8888438/108606507-67412080-7388-11eb-935a-8ae51397fe07.png)

https://github.com/redhat-actions/push-to-registry/runs/1943110175?check_suite_focus=true

**Comment by k3rnelpan1c-dev** [comment] 2021-02-20 19:44
Well I just changed the target registry to `quay` and I seem to get the same result tbh :confused: (aka I can reproduce this there too)
https://quay.io/repository/k3rnel-pan1c/dockerhub_ratelimit_exporter?tab=tags

**Comment by k3rnelpan1c-dev** [comment] 2021-02-20 19:52
the only difference I can see between our workflows is that I am using a "Containerfile" (aka. Dockerfile) to build the Image, while you seem to build from source

**Comment by k3rnelpan1c-dev** [comment] 2021-02-20 19:54
I'll install skopeo, just to see if I can see the same difference between the 2 tags as described in [this comment](https://github.com/containers/podman/issues/6496#issuecomment-670571198)

**Comment by k3rnelpan1c-dev** [comment] 2021-02-20 20:09
okay well this is interesting.
`skopeo inspect docker://quay.io/k3rnel-pan1c/dockerhub_ratelimit_exporter:unstable`
<details>
<summary>Output</summary>
<p>

```json
{
    "Name": "quay.io/k3rnel-pan1c/dockerhub_ratelimit_exporter",
    "Digest": "sha256:46fcdc9e5ce82ed4b4b3496075fbf25d6b29adc8839ddff5013757113ed44dc9",
    "RepoTags": [
        "unstable",
        "20f9b0c02c10738bae1af9ec73ad448eec1ef6df"
    ],
    "Created": "2021-02-20T19:42:35.949902314Z",
    "DockerVersion": "",
    "Labels": {
        "description": "A exporter for prometheus to check the pull limit of the DockerHub",
        "io.buildah.version": "1.19.2",
        "name": "dockerhub_ratelimit_exporter",
        "url": "https://github.com/dohq/dockerhub_ratelimit_exporter",
        "version": "1.1.0"
    },
    "Architecture": "amd64",
    "Os": "linux",
    "Layers": [
        "sha256:56d2cc464a85a998ee278fe62d1cfe82a5c6da1ae9b60ca35362d36defcd458a",
        "sha256:e116040e706ed480eb26cfb6709d460356f61227129835125ac12666e8c70b9a"
    ],
    "Env": [
        "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    ]
}
```

</p>  
</details>

`skopeo inspect docker://quay.io/k3rnel-pan1c/dockerhub_ratelimit_exporter:20f9b0c02c10738bae1af9ec73ad448eec1ef6df`

<details>
<summary>Output</summary>
<p>

```json
{
    "Name": "quay.io/k3rnel-pan1c/dockerhub_ratelimit_exporter",
    "Tag": "20f9b0c02c10738bae1af9ec73ad448eec1ef6df",
    "Digest": "sha256:55a559bee5ebf72faf691fe66ec08e0eb663043bc8322b652deef07e84aaef20",
    "RepoTags": [
        "unstable",
        "20f9b0c02c10738bae1af9ec73ad448eec1ef6df"
    ],
    "Created": "2021-02-20T19:42:35.949902314Z",
    "DockerVersion": "",
    "Labels": {
        "description": "A exporter for prometheus to check the pull limit of the DockerHub",
        "io.buildah.version": "1.19.2",
        "name": "dockerhub_ratelimit_exporter",
        "url": "https://github.com/dohq/dockerhub_ratelimit_exporter",
        "version": "1.1.0"
    },
    "Architecture": "amd64",
    "Os": "linux",
    "Layers": [
        "sha256:56d2cc464a85a998ee278fe62d1cfe82a5c6da1ae9b60ca35362d36defcd458a",
        "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4",
        "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4",
        "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4",
        "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4",
        "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4",
        "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4",
        "sha256:e116040e706ed480eb26cfb6709d460356f61227129835125ac12666e8c70b9a"
    ],
    "Env": [
        "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    ]
}
```

</p>  
</details>

**Comment by tetchel** [comment] 2021-02-21 22:12
I tried a dockerfile build, and also added a LABEL to my dockerfile because I noticed yours had some and mine didn't. [workflow](https://github.com/tetchel/express-ts/runs/1947702578?check_suite_focus=true)

Still, the SHAs match - and I used dockerhub, too.

![image](https://user-images.githubusercontent.com/8888438/108640478-ebb6a080-7467-11eb-9f2f-fe5110bee2a4.png)

I will try to dive deeper tomorrow...

**Comment by tetchel** [comment] 2021-02-22 18:28
hey @k3rnelpan1c-dev - I cloned your repo and went through the following steps [here](https://github.com/tetchel/dockerhub_ratelimit_exporter/actions)

1. changed the workflow to use my quay.io repo.
2. successfully reproduced your bug
3. Tried [this workaround](https://github.com/containers/image/issues/733#issuecomment-635682929) which worked, having the shas match.
4. Noticed that the podman version in your workflow was much older than the podman version in `push-to-registry`'s. This is because you targeted `ubuntu-latest` which is `18.04` while this repo uses `20.04`.
5. Removed the workaround and updated the ubuntu version
6. The bug went away!

So, this is indeed https://github.com/containers/image/issues/733 which appears to have been fixed in podman 3.0.0. You should be able to fix this for yourself by updating your workflow to use `runs-on: ubuntu-20.04`

**Comment by k3rnelpan1c-dev** [comment] 2021-02-22 18:37
Hi @tetchel. 

first of all THANK YOU for this detailed analysis and solution :+1: 
I am a bit annoyed about myself not thinking of something like this myself :sweat_smile: 

Regardless, this should maybe be noted in the readme  until GitHub / Microsoft have exchanged the image behind `ubuntu-latest` (at least in combination with trying to push multiple tags). I can open such a PR if you want me to.

Thank you for all the work and very quick resolution :tada:

**Closed** 2021-02-22 19:10 UTC
Labels: bug

**Comment by offa** [comment] 2021-09-01 09:49
@k3rnelpan1c-dev / @tetchel `ubuntu-latest` has moved to `20.04` this march; see https://github.com/actions/virtual-environments/issues/1816 or [available environments overview](https://github.com/actions/virtual-environments#available-environments).
